# Generated by Django 3.2.8 on 2022-01-31 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='static/images/tematicas/')),
                ('titulo', models.CharField(max_length=80)),
                ('resumen', models.CharField(max_length=300)),
                ('is_available', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('color1', models.CharField(max_length=9)),
                ('color2', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('answer_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='static/images/estudiantes/')),
                ('documento', models.BigIntegerField()),
                ('fechadenacimiento', models.DateField()),
                ('isPartner', models.BooleanField(default=False)),
                ('isSuperUser', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaUsuarioAbierta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('pregunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.pregunta')),
                ('userProfile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=80)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.curso')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.quiz'),
        ),
        migrations.CreateModel(
            name='OpcionRespuestaCerrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion_multiple', models.CharField(blank=True, max_length=100, null=True)),
                ('respuesta_correcta', models.BooleanField(blank=True, default=False, null=True)),
                ('pregunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nombre.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionRespuestaAbierta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('pregunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=80)),
                ('contenido_de_texto', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='static/images/material/')),
                ('video', models.URLField(blank=True, null=True)),
                ('materialExterno', models.URLField(blank=True, null=True)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.curso')),
                ('quizes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Enrolamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCreator', models.BooleanField(default=False)),
                ('isEnroled', models.BooleanField(default=False)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.curso')),
                ('userProfile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='tematica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.tematica'),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tiempo', models.TimeField()),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.quiz')),
                ('userProfile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.userprofile')),
            ],
        ),
    ]
