# Generated by Django 3.2.8 on 2021-11-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='titulo',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
