# Generated by Django 3.2.8 on 2022-01-17 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='quizes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.quiz'),
        ),
    ]
