# Generated by Django 3.2.8 on 2021-11-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tematica',
            name='resumen',
            field=models.CharField(max_length=300),
        ),
    ]
