# Generated by Django 3.2.8 on 2021-10-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tiempo', models.TimeField()),
                ('nota', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
