# Generated by Django 3.2.8 on 2022-01-31 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0002_alter_material_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='isPartner',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='isSuperUser',
        ),
    ]
