# Generated by Django 3.2.8 on 2022-01-17 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0002_material_quizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='quizes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.quiz'),
        ),
    ]
