# Generated by Django 3.2.8 on 2021-11-24 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nombre', '0002_alter_estudianteprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocenteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='static/images/docentes/')),
                ('documento', models.BigIntegerField()),
                ('fechadenacimiento', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='estudianteprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
