# Generated by Django 3.2.8 on 2021-12-03 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0002_auto_20211203_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudianteProfile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.estudianteprofile')),
                ('tematica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.tematica')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionRespuestaAbierta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('pregunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionRespuestaCerrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abierta', models.CharField(blank=True, max_length=100, null=True)),
                ('opcion_multiple', models.CharField(blank=True, max_length=100, null=True)),
                ('respuesta_correcta', models.BooleanField(blank=True, default=False, null=True)),
                ('pregunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEstudianteAbierta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('estudianteProfile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.estudianteprofile')),
                ('pregunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.pregunta')),
            ],
        ),
        migrations.DeleteModel(
            name='OpcionRespuesta',
        ),
    ]
