# Generated by Django 3.2.8 on 2021-10-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0002_auto_20211029_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='contenido_de_texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='material',
            name='materialExterno',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
