# Generated by Django 3.2.8 on 2022-02-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0003_auto_20220131_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(null=True, upload_to='static/images/categorias/'),
        ),
    ]
