# Generated by Django 3.2.8 on 2021-10-21 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0003_auto_20211021_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.estudiante'),
        ),
    ]
