# Generated by Django 3.2.8 on 2021-11-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0003_auto_20211029_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/material/'),
        ),
    ]
