# Generated by Django 3.2.8 on 2021-12-07 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0003_auto_20211203_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcionrespuestacerrada',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nombre.pregunta'),
        ),
    ]
