# Generated by Django 3.2.8 on 2022-03-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0004_categoria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionrespuestaabierta',
            name='valoracion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
