# Generated by Django 3.2.8 on 2021-12-07 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0004_alter_opcionrespuestacerrada_pregunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcionrespuestacerrada',
            name='abierta',
        ),
    ]
