# Generated by Django 3.2.8 on 2021-10-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0004_calificacion_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='tematica',
            name='Titulo',
            field=models.CharField(default='titulo', max_length=40),
            preserve_default=False,
        ),
    ]
