# Generated by Django 3.2.8 on 2021-10-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0005_tematica_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_de_texto', models.TextField(null=True)),
                ('imagen', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='tematica',
            old_name='Titulo',
            new_name='titulo',
        ),
    ]
