# Generated by Django 3.2.8 on 2022-03-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0005_opcionrespuestaabierta_valoracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalabrasClaveRespuestaAbierta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'PalabrasClaveRespuestaAbierta',
                'verbose_name_plural': 'PalabrasClaveRespuestaAbiertas',
            },
        ),
    ]
