# Generated by Django 3.2.8 on 2021-10-21 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0007_auto_20211021_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_corto', models.CharField(max_length=100, null=True)),
                ('texto_largo', models.TextField()),
                ('opcion_logica', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.quiz')),
            ],
        ),
    ]
