# Generated by Django 3.2.8 on 2022-03-09 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0007_alter_opcionrespuestaabierta_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='palabrasclaverespuestaabierta',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nombre.pregunta'),
        ),
    ]
