# Generated by Django 3.2.8 on 2021-10-21 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0008_opcionrespuesta_pregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_correcta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.opcionrespuesta')),
            ],
        ),
    ]
