# Generated by Django 3.2.8 on 2022-03-25 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0008_palabrasclaverespuestaabierta_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolamiento',
            name='userProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nombre.userprofile'),
        ),
    ]
