# Generated by Django 3.2.8 on 2021-10-21 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0011_opcionrespuesta_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='tematica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nombre.tematica'),
        ),
    ]
