# Generated by Django 3.2.8 on 2021-10-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0012_material_tematica'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
