# Generated by Django 3.2.8 on 2021-10-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombre', '0013_auto_20211022_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='documento',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='documento',
            field=models.BigIntegerField(),
        ),
    ]
